name: PR Authorization Check

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  check_authorization:
    runs-on: ubuntu-latest
    steps:
      - name: Check Authorization
        run: |
          authorized_users=("devi854" "john_doe") # Add the GitHub usernames of authorized users here
          pr_author=$(jq -r ".pull_request.user.login" "$GITHUB_EVENT_PATH")
          if [[ ! " ${authorized_users[@]} " =~ " ${pr_author} " ]]; then
            echo "Unauthorized user: $pr_author"
            echo "::error::Unauthorized user: $pr_author" # Set an error message to fail the pull request status
            exit 1
          fi
