name: deploy
on:
  pull_request:
    branches:
      - main

env:
  github.event.pull_request.user.login: ${{ secrets.PRASAD_USERNAME }}

jobs:
  production-deploy:
    if: ${{ env.github.event.pull_request.user.login ==  github.event.pull_request.user.login }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      # Add your production deployment steps here
