name: Publish Python Notebooks to JFrog Artifactory

on:
  push:
    branches:
      - develop
env:
  DATABRICKS_HOST: https://adb-5630925069180830.10.azuredatabricks.net
  ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
  ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
  URL: https://durga1212.jfrog.io/artifactory/api/pypi/pypi
  

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: 3.8
        
      - name: setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3.2.0
        env:
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
          URL: https://durga1212.jfrog.io/artifactory/api/pypi/pypi
          
      - name: Zip
        run: |
          mkdir new/release
          cd ./new/release
          zip -r test.zip ./
          
      - name: upload Package
        run: |
          jfrog rt u ./new/release/test.zip pypi/ght/ --build-name=my-build --build-number=${{ github.run_number }}
          

