name: Publish Python Notebooks to JFrog Artifactory

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install jfrog-artifactory

      - name: Publish notebooks to JFrog Artifactory
        uses: jfrog/artifactory-upload-action@v2
        with:
          server-id: default
          spec: |
            {
              "files": [
                {
                  "pattern": "notebooks/*.ipynb",
                  "target": "notebooks/"
                }
              ]
            }
          fail-fast: true
