name: Publish Python Notebooks to JFrog Artifactory

on:
  push:
    branches:
      - develop
env:
  DATABRICKS_HOST: https://adb-5630925069180830.10.azuredatabricks.net
  ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
  ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
  URL: https://durga1212.jfrog.io/artifactory/api/pypi/pypi
  

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: 3.8
          
      - name: Zip files
        run: zip -r archive.zip . -i test.py
        
      - name: Zip repository contents
        run: |
          zip -r myrepo.zip .          
        
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: myrepo
          path: myrepo.zip
          
      - name: setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3.2.0
        env:
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
          URL: https://durga1212.jfrog.io/artifactory/generic-release/
          
          
      - name: upload Package
        run: |
          jfrog rt u myrepo.zip generic-release --url=https://durga1212.jfrog.io/artifactory/generic-release/ --build-name=my-build --build-number=${{ github.run_number }}
          

