name: deploy

on:
  
  push:
    branches:
      - feature-0001
    
     
env:
  INSTANCE_POOL_ID: scp/123.sh

  

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: test
        run: |
          instance_pool_id: ${{ env.INSTANCE_POOL_ID }}
          
