name: deploy

on:
  
  push:
    branches:
      - feature-0001
    
     


  

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: test
        run: |
          chmod u+rw /scp/123.sh

          instance_pool_id="$( scp/123.sh )"
          
