name: deploy
on:
  push:
    branches:
      - main
    paths:
      - 'new-proj/**'
 
  
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          path: './new-proj'
      - name: Change working directory
        working-directory: /new-proj
        run: Tailspin.SpaceGame.Web.csproj
          
      - name: .Net Build
        uses: EasyDesk/action-dotnet-build@v1.0.0
        with:
          path: './new-proj/'
          
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.202'
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release
      - name: Publish
        run: dotnet publish --no-restore --configuration Release --output publish
          
