name: deploy
on:
  push:
    branches:
      - main
    paths:
      - 'new-proj/**'
 
  
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          path: 'new-proj'
